steps:
  # Install dependencies
  - name: 'python:3.9-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/baked-by-aisha',
        '.'
      ]

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/baked-by-aisha']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'baked-by-aisha',
        '--image',
        'gcr.io/$PROJECT_ID/baked-by-aisha',
        '--region',
        'us-south1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

# Specify that the built container is stored in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/baked-by-aisha'
