steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/baked-by-aisha', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/baked-by-aisha']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'baked-by-aisha',
         '--image', 'gcr.io/$PROJECT_ID/baked-by-aisha',
         '--platform', 'managed',
         '--region', 'us-central1',
         '--allow-unauthenticated']
